### ISSUE TITLE
Intermittent: Pipeline builds stop working after a while

### ISSUE THREAD

**Issue by csrwng** [openshift/openshift-jenkins-sync-plugin#113]
From https://bugzilla.redhat.com/show_bug.cgi?id=1406306

```
How reproducible:
Sometimes

Steps to Reproduce:
1. Create project xxia-pipeline
2. Create jenkins pipeline BC
$ oc new-app -f https://raw.githubusercontent.com/openshift/origin/master/examples/jenkins/pipeline/samplepipeline.yaml
3. Wait for jenkins pod to be running
4. Start jenkins pipeline builds
$ oc start-build sample-pipeline

Actual results:
4. At beginning, pipeline builds can succeed. But later it is found that, pipeline becomes not working. New pipeline build status is always "New":
[tester@pc_f25 oc]$ oc get build
NAME                       TYPE              FROM          STATUS     STARTED        DURATION
nodejs-mongodb-example-1   Source            Git@343689f   Complete   23 hours ago   2m58s
...
sample-pipeline-1          JenkinsPipeline                 Complete   23 hours ago   5m44s
...
sample-pipeline-4          JenkinsPipeline                 New

Check pod:
[tester@pc_f25 oc]$ oc get pod
NAME                             READY     STATUS      RESTARTS   AGE
jenkins-1-oj83m                  1/1       Running     1          23h
...

[tester@pc_f25 oc]$ oc logs pod/jenkins-1-oj83m
It outputs many repeated stuffs:

......

Dec 20, 2016 8:16:08 AM io.fabric8.jenkins.openshiftsync.BuildConfigWatcher onInitialBuildConfigs
SEVERE: Failed to update job
java.lang.IllegalArgumentException: Jenkins already contains an item 'xxia-pipeline-sample-pipeline'
    at hudson.model.ItemGroupMixIn.createProjectFromXML(ItemGroupMixIn.java:264)
    at jenkins.model.Jenkins.createProjectFromXML(Jenkins.java:3689)
    at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2.call(BuildConfigWatcher.java:214)
    at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2.call(BuildConfigWatcher.java:159)
    at hudson.security.ACL.impersonate(ACL.java:221)
    at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.upsertJob(BuildConfigWatcher.java:159)
    at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.onInitialBuildConfigs(BuildConfigWatcher.java:129)
    at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.access$200(BuildConfigWatcher.java:65)
    at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$1.doRun(BuildConfigWatcher.java:88)
    at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Dec 20, 2016 8:16:18 AM io.fabric8.jenkins.openshiftsync.BuildConfigWatcher onInitialBuildConfigs
SEVERE: Failed to update job
java.lang.IllegalArgumentException: Jenkins already contains an item 'xxia-pipeline-sample-pipeline'
    at hudson.model.ItemGroupMixIn.createProjectFromXML(ItemGroupMixIn.java:264)
    at jenkins.model.Jenkins.createProjectFromXML(Jenkins.java:3689)
    at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2.call(BuildConfigWatcher.java:214)
    at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2.call(BuildConfigWatcher.java:159)
    at hudson.security.ACL.impersonate(ACL.java:221)
    at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.upsertJob(BuildConfigWatcher.java:159)
    at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.onInitialBuildConfigs(BuildConfigWatcher.java:129)
    at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.access$200(BuildConfigWatcher.java:65)
    at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$1.doRun(BuildConfigWatcher.java:88)
    at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Expected results:
4. Pipeline build should always work
```

**Comment by csrwng** [comment]
@jimmidyson fyi
